name: 'dbt_training'
version: '1.0.0'
config-version: 2

profile: 'dbt_training'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  default_date: '9999-01-01'

models:
  dbt_training:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
