name: Scheduled Prod Runs

on:
  schedule:
    - cron: '21 * * * *' # Runs every hour at 21st minute

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    env:
      DBT_USER: ${{ secrets.DBT_USER }}
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Deploy & Test Models (PROD)
        run: dbt build --profiles-dir . --target prod

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target
